"""empty message

Revision ID: 01f41a18e7db
Revises: 72203d971f10
Create Date: 2021-01-15 09:51:26.687624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01f41a18e7db'
down_revision = '72203d971f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('dia_fechamento', sa.Integer(), nullable=True))
    op.add_column('propostas', sa.Column('dia_vencimento', sa.Integer(), nullable=True))
    op.add_column('propostas', sa.Column('prazo_vencimento', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('vigencia_final', sa.Date(), nullable=True))
    op.add_column('propostas', sa.Column('vigencia_inicial', sa.Date(), nullable=True))
    op.drop_column('propostas', 'vigenciaFinal')
    op.drop_column('propostas', 'vigenciaInicial')
    op.drop_column('propostas', 'diaVencimento')
    op.drop_column('propostas', 'diaFechamento')
    op.drop_column('propostas', 'prazoVencimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('prazoVencimento', sa.DATE(), nullable=True))
    op.add_column('propostas', sa.Column('diaFechamento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('propostas', sa.Column('diaVencimento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('propostas', sa.Column('vigenciaInicial', sa.DATE(), nullable=True))
    op.add_column('propostas', sa.Column('vigenciaFinal', sa.DATE(), nullable=True))
    op.drop_column('propostas', 'vigencia_inicial')
    op.drop_column('propostas', 'vigencia_final')
    op.drop_column('propostas', 'prazo_vencimento')
    op.drop_column('propostas', 'dia_vencimento')
    op.drop_column('propostas', 'dia_fechamento')
    # ### end Alembic commands ###
