"""empty message

Revision ID: 345511fd7da5
Revises: 3c0cc3e6a09c
Create Date: 2021-01-15 14:30:31.352519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345511fd7da5'
down_revision = '3c0cc3e6a09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('propostas_ibfk_1', 'propostas', type_='foreignkey')
    op.create_foreign_key(None, 'propostas', 'user', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propostas', type_='foreignkey')
    op.create_foreign_key('propostas_ibfk_1', 'propostas', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
