"""empty message

Revision ID: 3c0cc3e6a09c
Revises: 
Create Date: 2021-01-15 14:25:39.377465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c0cc3e6a09c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propostas', 'cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'propostas', 'clientes', ['cliente_id'], ['id'])
    op.drop_column('propostas', 'cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('cliente', mysql.VARCHAR(length=125), nullable=True))
    op.drop_constraint(None, 'propostas', type_='foreignkey')
    op.alter_column('propostas', 'cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
