"""empty message

Revision ID: 4711f75d7c2e
Revises: 01f41a18e7db
Create Date: 2021-01-15 13:35:41.899496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4711f75d7c2e'
down_revision = '01f41a18e7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('frequencia_anal_contra_int', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('frequencia_consultoria', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('frequencia_investigacao', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('frequencia_pentest', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('frequencia_ri', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('horas_mes_anal_contra_int', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('horas_mes_consultoria', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('horas_mes_investigacao', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('horas_mes_pentest', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('horas_mes_ri', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('total_cumulativo_anal_contra_int', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('total_cumulativo_consultoria', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('total_cumulativo_investigacao', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('total_cumulativo_pentest', sa.String(length=40), nullable=True))
    op.add_column('propostas', sa.Column('total_cumulativo_ri', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'total_cumulativo_ri')
    op.drop_column('propostas', 'total_cumulativo_pentest')
    op.drop_column('propostas', 'total_cumulativo_investigacao')
    op.drop_column('propostas', 'total_cumulativo_consultoria')
    op.drop_column('propostas', 'total_cumulativo_anal_contra_int')
    op.drop_column('propostas', 'horas_mes_ri')
    op.drop_column('propostas', 'horas_mes_pentest')
    op.drop_column('propostas', 'horas_mes_investigacao')
    op.drop_column('propostas', 'horas_mes_consultoria')
    op.drop_column('propostas', 'horas_mes_anal_contra_int')
    op.drop_column('propostas', 'frequencia_ri')
    op.drop_column('propostas', 'frequencia_pentest')
    op.drop_column('propostas', 'frequencia_investigacao')
    op.drop_column('propostas', 'frequencia_consultoria')
    op.drop_column('propostas', 'frequencia_anal_contra_int')
    # ### end Alembic commands ###
