"""empty message

Revision ID: 6e807dbfe507
Revises: 345511fd7da5
Create Date: 2021-01-15 14:59:11.682867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e807dbfe507'
down_revision = '345511fd7da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('celular', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('cpf_cnpj', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('exames', sa.Boolean(), nullable=True))
    op.add_column('clientes', sa.Column('nome_completo', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('rg', sa.String(length=40), nullable=True))
    op.drop_constraint('propostas_ibfk_1', 'propostas', type_='foreignkey')
    op.create_foreign_key(None, 'propostas', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propostas', type_='foreignkey')
    op.create_foreign_key('propostas_ibfk_1', 'propostas', 'user', ['cliente_id'], ['id'])
    op.drop_column('clientes', 'rg')
    op.drop_column('clientes', 'nome_completo')
    op.drop_column('clientes', 'exames')
    op.drop_column('clientes', 'cpf_cnpj')
    op.drop_column('clientes', 'celular')
    # ### end Alembic commands ###
