"""empty message

Revision ID: 72203d971f10
Revises: 7a9669c6a599
Create Date: 2021-01-15 09:43:43.164081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72203d971f10'
down_revision = '7a9669c6a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('setor', sa.String(length=125), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'setor')
    # ### end Alembic commands ###
