"""empty message

Revision ID: aaecefa1c1be
Revises: f8039e1a8f42
Create Date: 2021-01-15 15:24:07.216159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaecefa1c1be'
down_revision = 'f8039e1a8f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('bairro', sa.String(length=40), nullable=True))
    op.add_column('clientes', sa.Column('cidade', sa.String(length=40), nullable=True))
    op.add_column('clientes', sa.Column('data_nascimento', sa.DateTime(), nullable=True))
    op.add_column('clientes', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('estado', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'estado')
    op.drop_column('clientes', 'email')
    op.drop_column('clientes', 'data_nascimento')
    op.drop_column('clientes', 'cidade')
    op.drop_column('clientes', 'bairro')
    # ### end Alembic commands ###
