"""empty message

Revision ID: cc8ff8e0a2f3
Revises: 0c85a5299c5b
Create Date: 2021-01-15 15:17:55.857894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc8ff8e0a2f3'
down_revision = '0c85a5299c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('endereco', sa.String(length=255), nullable=True))
    op.drop_column('clientes', 'enedereco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('enedereco', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('clientes', 'endereco')
    # ### end Alembic commands ###
