"""empty message

Revision ID: f8039e1a8f42
Revises: cc8ff8e0a2f3
Create Date: 2021-01-15 15:19:20.882114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8039e1a8f42'
down_revision = 'cc8ff8e0a2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'data_nascimento')
    op.drop_column('clientes', 'email')
    op.drop_column('clientes', 'cidade')
    op.drop_column('clientes', 'estado')
    op.drop_column('clientes', 'observacoes')
    op.drop_column('clientes', 'bairro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('bairro', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('clientes', sa.Column('observacoes', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('clientes', sa.Column('estado', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('clientes', sa.Column('cidade', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('clientes', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('clientes', sa.Column('data_nascimento', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
