version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: app/app
    
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    env_file: 
      - .env
    depends_on:
      - db
    links:
      - redis

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: app 

  redis:
    image: 'redis:6.0.5-alpine'
    command: redis-server
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - redis_db:/data
    env_file: 
      - .env

volumes:
  redis_db:
  db_data:
